CREATE SCHEMA IF NOT EXISTS "Production";

CREATE TABLE IF NOT EXISTS "Production".users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INTEGER,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
        CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Production".hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    description TEXT
);

CREATE TABLE IF NOT EXISTS "Production".rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    room_number VARCHAR(255) NOT NULL,
    hotel_id BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL
        CHECK (category IN ('NORMAL', 'DELUXE')),
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),

    CONSTRAINT uk_rooms_hotel_number
        UNIQUE (hotel_id, room_number),
    CONSTRAINT fk_rooms_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES "Production".hotels (id)
);

CREATE TABLE IF NOT EXISTS "Production".bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_bookings_date_range
        CHECK (start_date < end_date),
    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)
        REFERENCES "Production".users (id),
    CONSTRAINT fk_bookings_room
        FOREIGN KEY (room_id)
        REFERENCES "Production".rooms (id)
);

CREATE TABLE IF NOT EXISTS "Production".payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    booking_id BIGINT NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    paid_amount NUMERIC(12, 2) NOT NULL CHECK (paid_amount >= 0),
    remaining_amount NUMERIC(12, 2) NOT NULL CHECK (remaining_amount >= 0),
    method VARCHAR(20) NOT NULL
        CHECK (method IN ('CARD', 'BKASH', 'CASH')),
    status VARCHAR(30) NOT NULL
        CHECK (status IN
               ('PENDING', 'PARTIALLY_PAID', 'PAID', 'FAILED', 'REFUNDED')),
    transaction_id VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id)
        REFERENCES "Production".bookings (id)
);

CREATE INDEX IF NOT EXISTS idx_hotels_city
    ON "Production".hotels (city);

CREATE INDEX IF NOT EXISTS idx_rooms_hotel_id
    ON "Production".rooms (hotel_id);

CREATE INDEX IF NOT EXISTS idx_rooms_filters
    ON "Production".rooms (hotel_id, capacity, category, price);

CREATE INDEX IF NOT EXISTS idx_bookings_user_id
    ON "Production".bookings (user_id);

CREATE INDEX IF NOT EXISTS idx_bookings_room_dates_status
    ON "Production".bookings (room_id, start_date, end_date, status);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payments_paid_transaction_id
    ON "Production".payments (transaction_id)
    WHERE status = 'PAID' AND transaction_id IS NOT NULL;
